import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        {/* Sticky Global Navigation */}
        <header className="sticky top-0 z-50 glass-panel border-b border-white/10 px-6 py-4">
          <div className="max-w-7xl mx-auto flex items-center">
            <a href="/" className="flex items-center gap-3 group transition-opacity hover:opacity-80">
              <img 
                src="/logo.png" 
                alt="ClimaSentinel Logo" 
                className="w-8 h-8 object-contain transition-transform group-hover:scale-105"
              />
              <span className="font-black text-xl tracking-wide text-slate-100">
                ClimaSentinel
              </span>
            </a>
          </div>
        </header>

        {/* Main Content */}
        <div className="flex-1">
          {children}
        </div>
      </body>
    </html>
  );
}
