#!/usr/bin/env bash
# =============================================================================
# ClimaSentinel — Terraform State Bootstrap
# =============================================================================
# Creates a GCS bucket to store Terraform remote state and generates the
# backend.tf configuration file.
#
# Usage:
#   chmod +x infra/bootstrap.sh
#   ./infra/bootstrap.sh
#
# Prerequisites:
#   - gcloud CLI installed & authenticated (gcloud auth login)
#   - Sufficient IAM permissions (Storage Admin on the project)
# =============================================================================

set -euo pipefail

# ─── Load .env from repo root ────────────────────────────────────────────────
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
ENV_FILE="$SCRIPT_DIR/../.env"

if [[ -f "$ENV_FILE" ]]; then
  # shellcheck disable=SC1090
  source "$ENV_FILE"
else
  echo -e "\033[1;33m[WARN]\033[0m  No .env file found at $ENV_FILE"
  echo -e "       Copy .env.example to .env and fill in GCP_PROJECT_ID."
fi
# ─────────────────────────────────────────────────────────────────────────────

# ─── Configuration ────────────────────────────────────────────────────────────
# Values come from .env — do not hard-code secrets here
PROJECT_ID="${GCP_PROJECT_ID:-your-gcp-project-id}"
REGION="${GCP_REGION:-europe-west9}"                   # default: Paris
BUCKET_NAME="${TF_STATE_BUCKET:-${PROJECT_ID}-tf-state}"
TERRAFORM_DIR="$(dirname "$0")/terraform"
# ──────────────────────────────────────────────────────────────────────────────

# ─── Colours ──────────────────────────────────────────────────────────────────
GREEN='\033[0;32m'; YELLOW='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'
info()    { echo -e "${GREEN}[INFO]${NC}  $*"; }
warn()    { echo -e "${YELLOW}[WARN]${NC}  $*"; }
error()   { echo -e "${RED}[ERROR]${NC} $*" >&2; exit 1; }
# ──────────────────────────────────────────────────────────────────────────────

# ─── Preflight checks ─────────────────────────────────────────────────────────
command -v gcloud >/dev/null 2>&1 || error "gcloud CLI not found. Install it from https://cloud.google.com/sdk"
command -v terraform >/dev/null 2>&1 || warn "terraform not found — skipping 'terraform init'. Install it to complete setup."

if [[ "$PROJECT_ID" == "your-gcp-project-id" ]]; then
  error "Set your GCP project ID via GCP_PROJECT_ID env var or edit this script."
fi

info "Project  : $PROJECT_ID"
info "Region   : $REGION"
info "Bucket   : gs://$BUCKET_NAME"
echo ""
read -rp "Proceed? [y/N] " confirm
[[ "$confirm" =~ ^[Yy]$ ]] || { warn "Aborted."; exit 0; }
# ──────────────────────────────────────────────────────────────────────────────

# ─── Set active project ───────────────────────────────────────────────────────
info "Setting active GCP project..."
gcloud config set project "$PROJECT_ID"
# ──────────────────────────────────────────────────────────────────────────────

# ─── Enable required APIs ─────────────────────────────────────────────────────
info "Enabling required GCP APIs..."
gcloud services enable \
  storage.googleapis.com \
  cloudresourcemanager.googleapis.com \
  --project="$PROJECT_ID"
# ──────────────────────────────────────────────────────────────────────────────

# ─── Create GCS bucket ────────────────────────────────────────────────────────
if gsutil ls -b "gs://$BUCKET_NAME" >/dev/null 2>&1; then
  warn "Bucket gs://$BUCKET_NAME already exists — skipping creation."
else
  info "Creating GCS bucket gs://$BUCKET_NAME ..."
  gsutil mb \
    -p "$PROJECT_ID" \
    -l "$REGION" \
    -b on \
    "gs://$BUCKET_NAME"
  info "Bucket created."
fi
# ──────────────────────────────────────────────────────────────────────────────

# ─── Enable versioning (protects state file history) ─────────────────────────
info "Enabling object versioning on the bucket..."
gsutil versioning set on "gs://$BUCKET_NAME"
# ──────────────────────────────────────────────────────────────────────────────

# ─── Enable soft delete / retention for safety ───────────────────────────────
info "Setting 30-day object retention policy..."
gsutil retention set 30d "gs://$BUCKET_NAME" 2>/dev/null || \
  warn "Could not set retention policy (may require org policy). Skipping."
# ──────────────────────────────────────────────────────────────────────────────

# ─── Prevent public access ────────────────────────────────────────────────────
info "Enforcing uniform bucket-level access (no public access)..."
gsutil uniformbucketlevelaccess set on "gs://$BUCKET_NAME"
# ──────────────────────────────────────────────────────────────────────────────

# ─── Generate backend.tf ──────────────────────────────────────────────────────
BACKEND_FILE="$TERRAFORM_DIR/backend.tf"
info "Generating $BACKEND_FILE ..."

cat > "$BACKEND_FILE" <<EOF
# Auto-generated by infra/bootstrap.sh — do not edit manually.
terraform {
  backend "gcs" {
    bucket = "$BUCKET_NAME"
    prefix = "terraform/state"
  }
}
EOF

info "backend.tf written."
# ──────────────────────────────────────────────────────────────────────────────

# ─── Run terraform init ───────────────────────────────────────────────────────
if command -v terraform >/dev/null 2>&1; then
  info "Running terraform init in $TERRAFORM_DIR ..."
  terraform -chdir="$TERRAFORM_DIR" init
else
  warn "terraform not found — run 'terraform init' manually in $TERRAFORM_DIR after installing it."
fi
# ──────────────────────────────────────────────────────────────────────────────


# ─── BigQuery cost cap (1 GB max per query) ───────────────────────────────────
BQ_ALIAS="alias bq='bq --maximum_bytes_billed=1073741824'"
BASHRC="$HOME/.bashrc"

if grep -qF "maximum_bytes_billed" "$BASHRC" 2>/dev/null; then
  warn "BQ cost cap alias already set in $BASHRC — skipping."
else
  echo "$BQ_ALIAS" >> "$BASHRC"
  # shellcheck disable=SC1090
  source "$BASHRC"
  info "BQ cost cap set: max 1 GB scanned per query (~\$0.005 max)."
fi
# ──────────────────────────────────────────────────────────────────────────────

echo ""
info "Bootstrap complete!"
info "GCS bucket  : gs://$BUCKET_NAME"
info "Backend file: $BACKEND_FILE"
info "BQ cap      : 1 GB max per query (alias in ~/.bashrc)"
info "Next steps  : add your resources to infra/terraform/ and run 'terraform plan'."
