"""
Starter tests for the ClimaSentinel backend.
These run automatically in CI on every PR → dev.
"""

import pytest
from unittest.mock import patch, MagicMock
from fastapi.testclient import TestClient

from app.main import app

client = TestClient(app)


# ── Unit Tests ───────────────────────────────────────────────────────────
# Unit tests verify the logic of individual parts of the application in isolation.
# They are fast and do not rely on external services, databases, or complex setups.

# This test verifies that the root API endpoint returns a 200 OK status 
# and the correct service information (name and version).
def test_root_returns_service_info():
    """GET / should return service name and version."""
    resp = client.get("/")
    assert resp.status_code == 200
    body = resp.json()
    assert "service" in body
    assert "version" in body
    assert body["service"] == "ClimaSentinel Backend"


# This test verifies that the health check endpoint returns a 200 OK status 
# and explicitly indicates the app is "healthy".
def test_health_returns_healthy():
    """GET /health should return status healthy."""
    resp = client.get("/health")
    assert resp.status_code == 200
    body = resp.json()
    assert body["status"] == "healthy"


# This test verifies that the health check endpoint provides a valid 
# uptime counter that is at least 0 seconds.
def test_health_contains_uptime():
    """GET /health should include uptime_seconds >= 0."""
    resp = client.get("/health")
    body = resp.json()
    assert "uptime_seconds" in body
    assert body["uptime_seconds"] >= 0


# ── Integration Tests ────────────────────────────────────────────────────
# Integration tests verify how different parts of the application work together,
# including interactions with middleware, real configurations, or external systems.

# This test simulates a cross-origin request from a frontend (e.g., localhost:3000)
# to verify that the backend correctly includes CORS headers allowing the request.
@pytest.mark.integration
def test_cors_headers_present():
    """Responses should include CORS headers for cross-origin requests."""
    resp = client.get("/", headers={"Origin": "http://localhost:3000"})
    assert resp.status_code == 200
    assert "access-control-allow-origin" in resp.headers


# This test verifies that the OpenAPI (Swagger) schema is successfully 
# generated by FastAPI and has the correct title.
@pytest.mark.integration
def test_openapi_schema_generation():
    """Ensure OpenAPI schema generates successfully."""
    response = client.get("/openapi.json")
    assert response.status_code == 200
    schema = response.json()
    assert "info" in schema
    assert schema["info"]["title"] == "ClimaSentinel Backend"

# This test checks the integration of the Prometheus Instrumentator,
# ensuring the /metrics endpoint is exposed and returning standard metric data.
@pytest.mark.integration
def test_integration_metrics_endpoint():
    """
    Test the integration of Prometheus Instrumentator.
    This ensures that the FastAPI middleware correctly exposes the /metrics endpoint.
    """
    resp = client.get("/metrics")
    assert resp.status_code == 200
    # Prometheus metrics are plain text, ensure it contains standard metrics
    assert "python_gc_" in resp.text or "http_requests" in resp.text


# This test verifies credential-failure handling without probing a real cloud
# metadata endpoint. CI and local tests must remain hermetic.
@pytest.mark.integration
def test_integration_bq_auth_failure_handling():
    """
    Test that a BigQuery credential failure is caught and cleanly returned as a
    500 response instead of crashing the server.
    """
    with patch(
        "app.main.get_bq_client",
        side_effect=RuntimeError("Application default credentials unavailable"),
    ):
        resp = client.get("/data/current-scores?limit=1")
    
    assert resp.status_code == 500
    assert "Failed to retrieve data" in resp.json()["detail"]

# ── Mock Data Tests ──────────────────────────────────────────────────────
# Mock tests use simulated objects (mocks) to replace real external dependencies
# like databases. This lets us test the application's logic handling the data
# without actually connecting to the real database.

# This test mocks the BigQuery client to return sample data. It verifies that
# the /data/current-scores endpoint correctly processes and returns this mock data.
@patch("app.db.bigquery.Client")
def test_get_current_scores_mocked(mock_bq_client):
    """
    Test the /data/current-scores endpoint with a mocked BigQuery client.
    """
    # Create a mock query job and result
    mock_query_job = MagicMock()
    mock_query_job.result.return_value = [
        {"city_id": "Paris", "current_tipping_score": 85.5},
        {"city_id": "London", "current_tipping_score": 72.1}
    ]
    
    # Configure the mock client to return our mock query job
    mock_client_instance = MagicMock()
    mock_client_instance.query.return_value = mock_query_job
    
    # Set the get_bq_client patch to return our mock client instance
    with patch("app.main.get_bq_client", return_value=mock_client_instance):
        response = client.get("/data/current-scores?limit=2")
        
        assert response.status_code == 200
        data = response.json()
        assert len(data) == 2
        assert data[0]["city_id"] == "Paris"
        assert data[0]["current_tipping_score"] == 85.5

# This test mocks an empty database response to verify that the API correctly
# returns a 404 Not Found error when no data exists for a given city.
@patch("app.db.bigquery.Client")
def test_get_city_scores_not_found(mock_bq_client):
    """
    Test that /data/city/{city_id}/scores returns 404 when the city is not found in BigQuery.
    """
    mock_query_job = MagicMock()
    mock_query_job.result.return_value = []
    
    mock_client_instance = MagicMock()
    mock_client_instance.query.return_value = mock_query_job
    
    with patch("app.main.get_bq_client", return_value=mock_client_instance):
        response = client.get("/data/city/UnknownCity/scores")
        
        assert response.status_code == 404
        assert "not found" in response.json()["detail"].lower()


# This test mocks a database connection error (like a timeout) to verify that
# the endpoint catches the exception and safely returns a 500 Internal Server Error.
@patch("app.db.bigquery.Client")
def test_get_history_scores_db_error(mock_bq_client):
    """
    Test that /data/history-scores cleanly returns a 500 error if BigQuery fails.
    """
    mock_client_instance = MagicMock()
    mock_client_instance.query.side_effect = Exception("BigQuery connection timeout")
    
    with patch("app.main.get_bq_client", return_value=mock_client_instance):
        response = client.get("/data/history-scores")
        
        assert response.status_code == 500
        assert response.json()["detail"] == "Failed to retrieve history data"
